name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

permissions: write-all

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.0.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install and Build
        run: |
          pnpm install --ignore-scripts
          pnpm run build

      - name: Deploy preview
        uses: access-nri/pr-preview-action@v2.1.1
        with:
          source-dir: ./dist/
          action: deploy
          umbrella-dir: preview
          pr-number: ${{ github.event.number }}
